performance and accessibility (issue #5)
n-aggarwal/comp-333-1 pull request #28
Opened 2023-10-04 18:37 UTC by aafrida

2023-10-04 23:20 UTC, n-aggarwal requested changes
If you look at the page speed insights for index.html you will see that the website is slow because of the embedded youtube videos. The image formats were but a minor issue, if you want to fix the performance issue, replace the youtube video with a lightweight static html webpage, perhaps one of our making.

2023-10-04 23:21 UTC, n-aggarwal commented
Also since you changes from `public` to `assets` which i am not sure why in the first place, please make sure to update the readme file so that the logo works properly.

2023-10-05 01:17 UTC, ananafrida commented on index.html
> +            <iframe loading="lazy" title="link"  width="420" height="345" src="index.html"></iframe>
replaced YT video with web link

2023-10-05 01:28 UTC, ananafrida commented
YT video was replaced with a web link before the comment was made. For a specific reference, a comment is left in the code under specific changes. Please check it. 

The folder was renamed to follow the conventional naming (minor issue). Usually, images and other project assets remain under "asset" folder.

readme file is updated accordingly. For future reference, try not to put any tags other than <li> under <ul>. That causes accessibility decrement.

Performance and accessibility tested and requirements met. Please find the pictures below.
![image](https://github.com/n-aggarwal/comp-333-1/assets/58756224/f6f0886c-becb-4d0b-82e4-b54d0a6dbe06)
![image](https://github.com/n-aggarwal/comp-333-1/assets/58756224/e715a057-bb7c-4078-9005-79a4b1660703)

2023-10-05 01:48 UTC, n-aggarwal approved these changes

2023-10-05 01:48 UTC, merged